OnBoardingPartyRentMVC/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OnBoardingPartyRentMVC.Data;
using OnBoardingPartyRentMVC.Models;

namespace OnBoardingPartyRentMVC.Controllers
{
    public class ProductController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ProductController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult IndexAdmin()
        {
            IEnumerable<Product> objProductList = _db.Products;
            return View(objProductList);
        }
    }
}

OnBoardingPartyRentMVC/Controllers/StoreController.cs
using Microsoft.AspNetCore.Mvc;
using OnBoardingPartyRentMVC.Data;
using OnBoardingPartyRentMVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace OnBoardingPartyRentMVC.Controllers
{
    public class StoreController : Controller
    {
        private readonly ApplicationDbContext _db;
        public StoreController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult IndexAdmin(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var store = from s in _db.Stores
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                store = store.Where(s => s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    store = store.OrderByDescending(s => s.Name);
                    break;
                case "Date":
                    store = store.OrderBy(s => s.CreatedDateTime);
                    break;
                case "date_desc":
                    store = store.OrderByDescending(s => s.CreatedDateTime);
                    break;
                default:
                    store = store.OrderBy(s => s.Name);
                    break;
            }
            return View(store.ToList());
            //IEnumerable<Store> objStoreList = _db.Stores;
            //return View(objStoreList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Store obj)
        {
            if (ModelState.IsValid)
            {
                return View(obj);
            }
            _db.Stores.Add(obj);
            _db.SaveChanges();
            TempData["success"] = "Store Added successfully!";
            return RedirectToAction("IndexAdmin");
        }

        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var storeFromDb = _db.Stores.Find(id);

            if (storeFromDb == null)
            {
                return NotFound();
            }
            return View(storeFromDb);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Store obj)
        {
            if (ModelState.IsValid)
            {
                return View(obj);
            }
            _db.Stores.Update(obj);
            _db.SaveChanges();
            TempData["success"] = "Store update successfully!";
            return RedirectToAction("IndexAdmin");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var obj = _db.Stores.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Stores.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Store delete successfully!";
            return RedirectToAction("IndexAdmin");
        }
    }
}

OnBoardingPartyRentMVC/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnBoardingPartyRentMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnBoardingPartyRentMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">RentalParty</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100 rounded-0 border-0" type="text" placeholder="Search" aria-label="Search">
        <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="#">Sign out</a>
        </div>
        </div>
    </header>
    <div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3 sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Admin">
              <span data-feather="home" class="align-text-bottom"></span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Store" asp-action="IndexAdmin">
              <span data-feather="file" class="align-text-bottom"></span>
              Store
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="IndexAdmin">
              <span data-feather="shopping-cart" class="align-text-bottom"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="IndexAdmin">
              <span data-feather="users" class="align-text-bottom"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Customer" asp-action="IndexAdmin">
              <span data-feather="users" class="align-text-bottom"></span>
              Cart
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2" class="align-text-bottom"></span>
              Comments
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
            @RenderBody()
        </div>
    </main>

    </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/admin.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnBoardingPartyRentMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnBoardingPartyRentMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnBoardingPartyRentMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnBoardingPartyRentMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Admin">Admin</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OnBoardingPartyRentMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OnBoardingPartyRentMVC/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <h2>@TempData["success"]</h2>
}

@if(TempData["error"] != null)
{
    <h2>@TempData["error"]</h2>
}